# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 184acea84ca8c95a13c282a96bae0c1147b3b530e531c8c887f1de4a88aef6829512df4fa40cfead80ead02430e27f65cdf4fcf07b2d9a73e96abe6ba0f56538

test:
  secret_key_base: dba1cf3650fed6ac8c1f3a1c7e5c1d6990fe363094a0decaa7ee9d47cd8f9236e29eb2071d7761398bb2f653f514d131bbe1741c6aa7ddfa9ecf1f6f029639ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
